-- MySQL Script generated by MySQL Workbench
-- Fri May 10 10:33:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema taw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema taw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `taw` DEFAULT CHARACTER SET latin1 ;
USE `taw` ;

-- -----------------------------------------------------
-- Table `taw`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw`.`usuario` (
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`correo`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taw`.`amigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw`.`amigo` (
  `usuario1` VARCHAR(45) NOT NULL,
  `usuario2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario1`, `usuario2`),
  INDEX `fk_amigo_usuario2_idx` (`usuario2` ASC) VISIBLE,
  CONSTRAINT `fk_amigo_usuario1`
    FOREIGN KEY (`usuario1`)
    REFERENCES `taw`.`usuario` (`correo`),
  CONSTRAINT `fk_amigo_usuario2`
    FOREIGN KEY (`usuario2`)
    REFERENCES `taw`.`usuario` (`correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taw`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw`.`grupo` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `privado` TINYINT(4) NOT NULL,
  `imagen` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = '	';


-- -----------------------------------------------------
-- Table `taw`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw`.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contenido` VARCHAR(45) NOT NULL,
  `privado` TINYINT(4) NOT NULL,
  `grupo_id` INT(11) NULL DEFAULT NULL,
  `usuario_correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `usuario_correo`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_post_grupo1_idx` (`grupo_id` ASC) VISIBLE,
  INDEX `fk_post_usuario1_idx` (`usuario_correo` ASC) VISIBLE,
  CONSTRAINT `fk_post_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `taw`.`grupo` (`id`),
  CONSTRAINT `fk_post_usuario1`
    FOREIGN KEY (`usuario_correo`)
    REFERENCES `taw`.`usuario` (`correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taw`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw`.`comentario` (
  `texto` LONGTEXT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `post_id` INT(11) NOT NULL,
  `usuario_correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`post_id`, `usuario_correo`),
  INDEX `fk_comentario_usuario1_idx` (`usuario_correo` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `taw`.`post` (`id`),
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_correo`)
    REFERENCES `taw`.`usuario` (`correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `taw`.`gruposusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `taw`.`gruposusuario` (
  `grupoId` INT(11) NOT NULL,
  `gruposusuariocol` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`grupoId`, `usuario_correo`),
  INDEX `fk_gruposusuario_usuario1_idx` (`usuario_correo` ASC) VISIBLE,
  CONSTRAINT `fk_gruposusuario_usuario1`
    FOREIGN KEY (`usuario_correo`)
    REFERENCES `taw`.`usuario` (`correo`),
  CONSTRAINT `grupoFK`
    FOREIGN KEY (`grupoId`)
    REFERENCES `taw`.`grupo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
